### ISSUE TITLE
Tweak layout of username/password flow on mobile

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#495] opened 2017-06-17 23:19 UTC
From scott:

"Mobile login screen – you have to scroll down after entering your username/email (it might make more sense to have it on one screen – there’s a white bar at the bottom that could maybe be done away with?)"

**Comment by andreadelrio** [comment] 2017-06-17 23:26
Please indicate device so I can reproduce? I don't see anything wrong from iPhone 5.
![image](https://user-images.githubusercontent.com/4016496/27256903-0587917c-5379-11e7-9198-ed11de095737.png)

**Comment by davidascher** [comment] 2017-06-17 23:27
This is from @scottofletcher, I don't know what phone (it's an android device).

Picture: 
![image](https://user-images.githubusercontent.com/51278/27256934-e9418d0a-5379-11e7-91ad-770ef33bc74b.png)

**Comment by davidascher** [comment] 2017-06-17 23:28
we may not have a lot of control over this auth0 dialog.

**Comment by andreadelrio** [comment] 2017-07-29 00:51
Closing for now as I can't seem to reproduce on Chrome's emulator or in an Android device.

**Closed by andreadelrio** 2017-07-29 00:51 UTC

**Comment by scottofletcher** [comment] 2017-07-29 22:00
I just tried it out again and it seems to be working fine - thanks guys!

**Comment by dethe** [comment] 2017-07-29 22:04
Excellent, glad it's working for you, @scottofletcher!

**Comment by scottofletcher** [comment] 2017-07-29 22:16
Thanks @dethe! Everything's looking great :)
